"""quitar contraseña unica

Revision ID: 05dde6c1c9d6
Revises: a3c05348c568
Create Date: 2024-10-09 21:12:52.542742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05dde6c1c9d6'
down_revision = 'a3c05348c568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('contrasenia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('contrasenia', ['contrasenia'], unique=True)

    # ### end Alembic commands ###
