"""usuario imagen url

Revision ID: 264069209b9b
Revises: 3317733cad34
Create Date: 2024-10-11 18:07:31.558879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264069209b9b'
down_revision = '3317733cad34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('imagen_perfil',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('imagen_perfil',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
