"""creacion de tabla ubicacion

Revision ID: 3317733cad34
Revises: c883d1d01d25
Create Date: 2024-10-10 09:05:26.617761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3317733cad34'
down_revision = 'c883d1d01d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubicacion',
    sa.Column('id_ubicacion', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.String(length=50), nullable=False),
    sa.Column('longitud', sa.String(length=50), nullable=False),
    sa.Column('Descripcion_ubicacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicacion')
    # ### end Alembic commands ###
