"""Cambio de los modelos a snake_case

Revision ID: 333f63c9ff55
Revises: a3c05348c568
Create Date: 2024-10-22 20:42:30.138779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '333f63c9ff55'
down_revision = 'a3c05348c568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_material',
    sa.Column('id_tipo_material', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_tipo_material', sa.String(length=50), nullable=False),
    sa.Column('descripcion_tipo_material', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_material')
    )
    op.create_table('ubicacion',
    sa.Column('id_ubicacion', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.String(length=50), nullable=False),
    sa.Column('longitud', sa.String(length=50), nullable=False),
    sa.Column('descripcion_ubicacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    op.create_table('direccion_entrega',
    sa.Column('id_direccion_entrega', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_destinatario', sa.String(length=100), nullable=False),
    sa.Column('descrip_direc_entrega', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('latitud_entrega', sa.String(length=50), nullable=True),
    sa.Column('longitud_entrega', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro_entrega', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_direccion_entrega')
    )
    op.create_table('interes',
    sa.Column('id_interes', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_seleccion', sa.DateTime(), nullable=True),
    sa.Column('id_tipo_material', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_material'], ['tipo_material.id_tipo_material'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_interes')
    )
    op.create_table('material',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('nombre_material', sa.String(length=100), nullable=False),
    sa.Column('cantidad_material', sa.Integer(), nullable=False),
    sa.Column('estado_material', sa.String(length=20), nullable=False),
    sa.Column('precio_material', sa.String(length=30), nullable=False),
    sa.Column('descripcion_material', sa.String(length=255), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_tipo_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_material'], ['tipo_material.id_tipo_material'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_material')
    )
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_material', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'material', ['id_material'], ['id_material'], ondelete='CASCADE')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('numero_telefono',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('imagen_perfil',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('contrasenia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('contrasenia', ['contrasenia'], unique=True)
        batch_op.alter_column('imagen_perfil',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('numero_telefono',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               nullable=False)

    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_material')

    op.drop_table('material')
    op.drop_table('interes')
    op.drop_table('direccion_entrega')
    op.drop_table('ubicacion')
    op.drop_table('tipo_material')
    # ### end Alembic commands ###
