"""creacion del campo QR en usuario

Revision ID: 42f2e6a41478
Revises: 76bd8c6e2493
Create Date: 2024-11-11 18:51:16.314478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f2e6a41478'
down_revision = '76bd8c6e2493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_qr', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('imagen_qr')

    # ### end Alembic commands ###
