"""agregado de fecha publicacion material

Revision ID: 4f716ab5fa81
Revises: de4e6a60679e
Create Date: 2024-10-24 15:59:06.894676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f716ab5fa81'
down_revision = 'de4e6a60679e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_publicacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('fecha_publicacion')

    # ### end Alembic commands ###
