"""creacion del modelo imagen para material

Revision ID: 52f740cd6f93
Revises: 42f2e6a41478
Create Date: 2024-11-11 20:43:45.518518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f740cd6f93'
down_revision = '42f2e6a41478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagen',
    sa.Column('id_imagen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen')
    # ### end Alembic commands ###
