"""creacion del modelo pedido

Revision ID: 6207e0bf3f3b
Revises: ba8af9b98a77
Create Date: 2024-11-12 17:20:26.647635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6207e0bf3f3b'
down_revision = 'ba8af9b98a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('estado_pedido', sa.String(length=20), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=False),
    sa.Column('total_pedido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nombre_destinatario_pedido', sa.String(length=30), nullable=False),
    sa.Column('descrip_direc_entrega_pedido', sa.String(length=255), nullable=True),
    sa.Column('telefono_ref_pedido', sa.String(length=20), nullable=False),
    sa.Column('latitud_entrega_pedido', sa.String(length=50), nullable=False),
    sa.Column('longitud_entrega_pedido', sa.String(length=50), nullable=False),
    sa.Column('precio_unitario_producto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    # ### end Alembic commands ###
