"""Correccion precio

Revision ID: 76bd8c6e2493
Revises: 6f5cbb0163f7
Create Date: 2024-11-06 23:24:40.252724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76bd8c6e2493'
down_revision = '6f5cbb0163f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('precio_material',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('precio_material',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
