"""Agregado el campo cantidad en pedido y actualizado nullable de algunos campos

Revision ID: 89bdf593d621
Revises: 6207e0bf3f3b
Create Date: 2024-11-19 22:42:38.217162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89bdf593d621'
down_revision = '6207e0bf3f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('cantidad_producto', sa.Numeric(precision=10, scale=2), nullable=False))

    # Modificar nullable de los campos existentes
    op.alter_column('pedido', 'nombre_destinatario_pedido', existing_type=sa.String(30), nullable=True)
    op.alter_column('pedido', 'descrip_direc_entrega_pedido', existing_type=sa.String(255), nullable=True)
    op.alter_column('pedido', 'telefono_ref_pedido', existing_type=sa.String(20), nullable=True)
    op.alter_column('pedido', 'latitud_entrega_pedido', existing_type=sa.String(50), nullable=True)
    op.alter_column('pedido', 'longitud_entrega_pedido', existing_type=sa.String(50), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir nullable de los campos
    op.alter_column('pedido', 'longitud_entrega_pedido', existing_type=sa.String(50), nullable=False)
    op.alter_column('pedido', 'latitud_entrega_pedido', existing_type=sa.String(50), nullable=False)
    op.alter_column('pedido', 'telefono_ref_pedido', existing_type=sa.String(20), nullable=False)
    op.alter_column('pedido', 'descrip_direc_entrega_pedido', existing_type=sa.String(255), nullable=False)
    op.alter_column('pedido', 'nombre_destinatario_pedido', existing_type=sa.String(30), nullable=False)

    # Eliminar la columna cantidad_producto
    op.drop_column('pedido', 'cantidad_producto')
    # ### end Alembic commands ###
