"""creacion del modelo guardado

Revision ID: ba8af9b98a77
Revises: 52f740cd6f93
Create Date: 2024-11-12 16:12:28.077279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8af9b98a77'
down_revision = '52f740cd6f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardado',
    sa.Column('id_guardado', sa.Integer(), nullable=False),
    sa.Column('fecha_guardado', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_guardado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardado')
    # ### end Alembic commands ###
