"""usuario con telefono de 20

Revision ID: c883d1d01d25
Revises: 39c71b05a9f2
Create Date: 2024-10-09 21:59:45.477001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c883d1d01d25'
down_revision = '05dde6c1c9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('numero_telefono',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('numero_telefono',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
