"""tipo de unidad de material agregado

Revision ID: cfa3155af19d
Revises: 4f716ab5fa81
Create Date: 2024-10-28 18:27:31.116395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa3155af19d'
down_revision = '4f716ab5fa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_unidad_material', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('tipo_unidad_material')

    # ### end Alembic commands ###
