"""nuevas tablas

Revision ID: e006f68abda3
Revises: 264069209b9b
Create Date: 2024-10-13 10:21:25.417126

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e006f68abda3"
down_revision = "264069209b9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "direccion_Entrega",
        sa.Column("id_direccionEntrega", sa.Integer(), nullable=False),
        sa.Column("nombre_destinatario", sa.String(length=100), nullable=False),
        sa.Column("descrip_direcEntrega", sa.String(length=255), nullable=False),
        sa.Column("telefono", sa.Integer(), nullable=False),
        sa.Column("latitud_entrega", sa.String(length=50), nullable=True),
        sa.Column("longitud_entrega", sa.String(length=50), nullable=True),
        sa.Column("fecha_registro_entrega", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id_direccionEntrega"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("direccion_Entrega")
    # ### end Alembic commands ###
