"""Telefono nulo

Revision ID: e37619dfffd5
Revises: a3c05348c568
Create Date: 2024-10-17 14:05:20.010227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e37619dfffd5'
down_revision = 'a3c05348c568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tipo_Material',
    sa.Column('id_tipoMaterial', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_tipo_material', sa.String(length=50), nullable=False),
    sa.Column('descripcion_tipoMaterial', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipoMaterial')
    )
    op.create_table('ubicacion',
    sa.Column('id_ubicacion', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.String(length=50), nullable=False),
    sa.Column('longitud', sa.String(length=50), nullable=False),
    sa.Column('Descripcion_ubicacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    op.create_table('Interes',
    sa.Column('id_interes', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_seleccion', sa.DateTime(), nullable=True),
    sa.Column('id_tipoMaterial', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipoMaterial'], ['Tipo_Material.id_tipoMaterial'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_interes')
    )
    op.create_table('direccion_entrega',
    sa.Column('id_direccionEntrega', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_destinatario', sa.String(length=100), nullable=False),
    sa.Column('descrip_direcEntrega', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('latitud_entrega', sa.String(length=50), nullable=True),
    sa.Column('longitud_entrega', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro_entrega', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_direccionEntrega')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('numero_telefono',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('imagen_perfil',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('contrasenia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('contrasenia', ['contrasenia'], unique=True)
        batch_op.alter_column('imagen_perfil',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('numero_telefono',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               nullable=False)

    op.drop_table('direccion_entrega')
    op.drop_table('Interes')
    op.drop_table('ubicacion')
    op.drop_table('Tipo_Material')
    # ### end Alembic commands ###
