"""Creacion tabla Tipo_Material e Interes

Revision ID: f39dcb27add0
Revises: e00f89440c07
Create Date: 2024-10-16 17:32:17.341733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39dcb27add0'
down_revision = 'e00f89440c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tipo_Material',
    sa.Column('id_tipoMaterial', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_tipo_material', sa.String(length=50), nullable=False),
    sa.Column('descripcion_tipoMaterial', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipoMaterial')
    )
    op.create_table('Interes',
    sa.Column('id_interes', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_seleccion', sa.DateTime(), nullable=True),
    sa.Column('id_tipoMaterial', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipoMaterial'], ['Tipo_Material.id_tipoMaterial'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_interes')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Interes')
    op.drop_table('Tipo_Material')
    # ### end Alembic commands ###
